@hostname = https://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json


### Get Products
GET {{host}}/api/products 

### Get Product
GET {{host}}/api/products/99 

### Create Product
POST {{host}}/api/products HTTP/1.1
content-type: application/json

{
    "name": "Product TEST TEST",
    "description": "Product TEST description",
    "price": 10.99,
    "productTypeId": 1,
    "productBrandId": 1
}

### Update Product
PUT {{host}}/api/products/5 HTTP/1.1
content-type: application/json

{
    "name": "Product TEST UPDATE",
    "description": "Product TEST description",
    "price": 555,
    "productTypeId": 1,
    "productBrandId": 1
}

### Delete Product
DELETE {{host}}/api/products/5 HTTP/1.1


